name: myporto
description: My Porto Web

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.2
  google_fonts: ^2.1.0
  responsive_builder: ^0.4.1
  provider: ^6.0.0
  url_launcher: ^6.0.10
  lorem_ipsum: ^0.0.1
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/